name: non-bhb-search
channels:
  - conda-forge
  - defaults
dependencies:
  - ptmcmcsampler==2.1.1
  - mpi4py==3.1.4
  - enterprise-pulsar==3.3.2
  - pip==22.3.1
  - compilers
  - h5py
  - pip:
    - git+https://github.com/dfm/acor.git@b55eb8efa7df6c73b6f3f0c9b64fa1c801e8f821
    - docopt==0.6.2
    - enterprise-extensions==2.4.0
    - NatPy==0.1.1
