# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: PTArcade
theme:
  name: material
  icon:
    logo: simple/applearcade
  features:
    - header.autohide
    - navigation.footer
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: deep purple
      toggle:
        name: Switch to dark mode
        icon: material/toggle-switch-off-outline
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to light mode

nav:
  - About: index.md
  - Install: installation.md
  - Inputs: inputs.md
  - Outputs: outputs.md
  - Usage: usage.md
  - Contributing: contributing.md
  - Code Overview: overview.md
  - Code Reference: reference/

plugins:
  - search:
      lang: en
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      watch:
        - src/ptarcade
      handlers:
        python:
          paths: [src]
          import:
          - https://enterprise.readthedocs.io/en/latest/objects.inv
          - http://jellis18.github.io/PTMCMCSampler/objects.inv
          options:
            selection:
              members: yes
            docstring_style: numpy
            docstring_section_style: table
            show_if_no_docstring: true
            separate_signature: true
            show_signature_annotations: true
            show_root_heading: false
            heading_level: 2
            group_by_category: true
            show_category_heading: true
            members_order: source


markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: false
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
