name: Singularity Build and Deploy
on:
  # Build on pushes to master
  push:
    branches:
      - master
    paths:
      - "./Singularity"
      - "./environment.yml"

  # Do the builds on PRs to master
  pull_request:
    branches:
      - master
    paths:
      - "./Singularity"
      - "./environment.yml"


jobs:
  build-test-containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        recipe: ["Singularity"]
        conda: ["environment.yml"]
        container: ["non-bhb-search.sif"]


    name: Setup and build
    steps:
      - name: Check out code for the container build
        uses: actions/checkout@v3

      - name: Continue if Singularity recipe and Conda env exist
        run: |
          if [ -f "${{ matrix.recipe }}" -a -f "${{ matrix.conda }}" ]; then
            echo "keepgoing=true" >> $GITHUB_ENV
          fi

      - name: Set up Go 1.19
        if: ${{ env.keepgoing == 'true' }}
        uses: actions/setup-go@v1
        with:
          go-version: 1.19.3
        id: go

      - name: Install Dependencies
        if: ${{ env.keepgoing == 'true' }}
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config
      - name: Install Singularity
        if: ${{ env.keepgoing == 'true' }}
        env:
          SINGULARITY_VERSION: 3.10.4
          GOPATH: /tmp/go

        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity-ce-${SINGULARITY_VERSION} && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install

      - name: Build Container
        if: ${{ env.keepgoing == 'true' }}
        env:
          recipe: ${{ matrix.recipe}}
        run: |
         ls
         if [ -f "${{ matrix.recipe }}" ]; then
            sudo -E singularity build ${{ matrix.container }} ${{ matrix.recipe }}
            tag=$(echo "${recipe/Singularity\./}")
            if [ "$tag" == "Singularity" ]; then
                tag=latest
            fi
            # Build the container and name by tag
            echo "Tag is $tag."
            echo "tag=$tag" >> $GITHUB_ENV
         else
           echo "${{ matrix.changed_file }} is not found."
           echo "Present working directory: $PWD"
           ls
         fi
      - name: Login and Deploy Container
        if: (github.event_name != 'pull_request')
        env:
          keepgoing: ${{ env.keepgoing }}
        run: |
            if [[ "${keepgoing}" == "true" ]]; then
                echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io
                singularity push ${{ matrix.container }} oras://ghcr.io/${github.repository}:${tag}
            fi
